ha[0]=RA
ra[0]=RA
ra[1]=E_AB
ra[2]=E_AC
hb[0]=RB
rb[0]=RB
rb[1]=E_AB
rb[2]=E_BE
rb[3]=E_BD
hc[0]=RC
rc[0]=RC
rc[1]=E_AC
rc[2]=E_CE
rc[3]=E_CD
hd[0]=RD
rd[0]=RD
rd[1]=E_CD
rd[2]=E_BD
re[0]=E_CE
re[1]=E_BE
re[bridged]=true
